name: Update Demo Env

permissions:
  id-token: write
  contents: read
  packages: write

on:
  workflow_dispatch:

jobs:
  copy-tag:
    runs-on: depot-ubuntu-22.04

    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Copy to demo tag
        run: |
          crane tag ghcr.io/${{ github.repository }}:latest demo
          crane tag docker.io/obot/${{ github.event.repository.name }}:latest demo
